model:
  path: '/home/jetbot/Student/Robotics-Dawid/model0_0_0.onnx'

robot:
  max_speed: 0.22
  max_steering: 1.0
  differential:
    left: 1.0
    right: 1.0
  
  postprocessing:
    speed: "mid"
    smooth: False
    hist_len: 4
