model:
  path: '/home/jetbot/Student/Robotics-Mateusz/model_1_2.onnx'

robot:
  max_speed: 0.15
  max_steering: 0.55
  differential:
    left: 1.0
    right: 1.0
  
  postprocessing:
    speed: "mid"
    smooth: False
    centre: False
    hist_len: 4
